---
ansible_downloads: ~/.ansible-downloads/
dotfiles_home: "~"

# Homebrew options
homebrew_upgrade_all_packages: no

configure_vagrant_sudoers: yes
configure_prefs: yes
configure_osx: yes

# Dotfiles options

# Bash Options
configure_dotfiles_bash: yes
dotfiles_repo: "https://github.com/chrismulderza/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/code/github/dotfiles

dotfiles_bash_files:
#  - .bash_profile
#  - .gitconfig
  - tmux.conf
  - tmux-osx.conf
#  - .inputrc
#  - .osx
#  - .vimrc

# Vim Options
configure_dotfiles_vim: yes
dotfiles_vim_files:
  - vimrc


homebrew_installed_packages:
  - autoconf
  - bash
  - bash-completion
  - bashdb
  - binutils
  - coreutils
  - direnv
  - doxygen
  - findutils
  - gettext
  - gpg
  - gradle
  - groovy
  - gsed
  - midnight-commander
  - nmap
  - packer
  - readline
  - ssh-copy-id
  - subversion
  - pv
  - tmux
  - tree
  - vim
    install_options --with-lua --with-python3
  - vpnc
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/fonts
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
#  - firefox
#  - google-chrome
#  - java
#  - kdiff3
#  - nvalt
  - skype
  - vagrant
  - virtualbox
  - vlc

