---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
#    - ansible-setup
#    - homebrew
#    - { role: dotfiles-bash, when: configure_dotfiles_bash }
    - { role: dotfiles-vim, when: configure_dotfiles_vim }

#  tasks:
#    - include: tasks/vagrant_sudo.yml
#      when: configure_vagrant_sudoers
#    - include: tasks/preferences.yml
#      when: configure_prefs
