---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml


  tasks:


    - include: tasks/setup-ansible.yml
    - include: tasks/setup-homebrew.yml
      when: homebrew_setup
    - include: tasks/setup-repo.yml
    - include: tasks/setup-dotfiles.yml
      when: dotfiles_setup
    - include: tasks/setup-vagrant.yml
      when: configure_vagrant
